package io.insource.framework.config

import io.insource.framework.annotation.ConditionalOnEnableZmqListener
import org.springframework.boot.context.properties.ConfigurationProperties
import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigurationProperties
@ConditionalOnEnableZmqListener
@ConfigurationProperties("zmq.listener")
internal class ZmqListenerProperties